In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

WEEK 1 ASSIGMNENT

In [2]:
df = pd.read_csv('/home/onyeogulu/www/node/mlbookcamp-code/chapter-02-car-price/data.csv')
len(df)

11914

In [46]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [47]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

string_columns = list(df.dtypes[df.dtypes == 'object'].index)

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [48]:
pd.value_counts(df.make)

chevrolet        1123
ford              881
volkswagen        809
toyota            746
dodge             626
nissan            558
gmc               515
honda             449
mazda             423
cadillac          397
mercedes-benz     353
suzuki            351
bmw               334
infiniti          330
audi              328
hyundai           303
volvo             281
subaru            256
acura             252
kia               231
mitsubishi        213
lexus             202
buick             196
chrysler          187
pontiac           186
lincoln           164
oldsmobile        150
land_rover        143
porsche           136
saab              111
aston_martin       93
plymouth           82
bentley            74
ferrari            69
fiat               62
scion              60
maserati           58
lamborghini        52
rolls-royce        31
lotus              29
tesla              18
hummer             17
maybach            16
alfa_romeo          5
mclaren             5
spyker    

In [49]:
df_audi = df[df.make == "audi"]

In [50]:
pd.value_counts(df_audi.model).count()

34

In [51]:
df.shape

(11914, 16)

In [52]:
df.dropna(axis =1).shape[0]

11914

In [53]:
df.shape[1]-df.dropna(axis =1).shape[1]

5

In [21]:
df.describe()

year    engine_hp  engine_cylinders  number_of_doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway_mpg      city_mpg    popularity          msrp  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [54]:
df.engine_cylinders.median()

6.0

In [55]:
pd.value_counts(df.engine_cylinders)

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: engine_cylinders, dtype: int64

In [56]:
df.engine_cylinders.mode()

0    4.0
Name: engine_cylinders, dtype: float64

In [57]:
df.engine_cylinders.fillna(df.engine_cylinders.mode()).median()

6.0

In [58]:
df_lotus = df[df.make == "lotus"]
df_lotus.head()

make  model  year             engine_fuel_type  engine_hp  \
3912  lotus  elise  2009  premium_unleaded_(required)      189.0   
3913  lotus  elise  2009  premium_unleaded_(required)      218.0   
3914  lotus  elise  2009  premium_unleaded_(required)      189.0   
3915  lotus  elise  2010  premium_unleaded_(required)      189.0   
3916  lotus  elise  2010  premium_unleaded_(required)      218.0   

      engine_cylinders transmission_type     driven_wheels  number_of_doors  \
3912               4.0            manual  rear_wheel_drive              2.0   
3913               4.0            manual  rear_wheel_drive              2.0   
3914               4.0            manual  rear_wheel_drive              2.0   
3915               4.0            manual  rear_wheel_drive              2.0   
3916               4.0            manual  rear_wheel_drive              2.0   

              market_category vehicle_size vehicle_style  highway_mpg  \
3912  exotic,high-performance      compact   convertible           27   
3913  exotic,high-performance      compact   convertible           26   
3914  exotic,high-performance      compact   convertible           27   
3915  exotic,high-performance      compact   convertible           27   
3916  exotic,high-performance      compact   convertible           26   

      city_mpg  popularity   msrp  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [59]:
len(df_lotus)

29

In [60]:
df_1 = df_lotus[["engine_hp","engine_cylinders"]]
df_1.head()

engine_hp  engine_cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [74]:
new_df_1 = df_1.drop_duplicates()
new_df_1

engine_hp  engine_cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [105]:
x = np.array(new_df_1).reshape(9, 2)
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [106]:
x.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [107]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [108]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [109]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [111]:
XTX = matrix_matrix_multiplication(x.T, x)

In [114]:
inverse_XTX = np.linalg.inv(XTX)

In [116]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [119]:
X_1= matrix_matrix_multiplication(inverse_XTX, x.T)

X_1

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [120]:
matrix_vector_multiplication(X_1,y)

array([  4.59494481, -63.56432501])